### ISSUE TITLE
Can you tell any benefits when the projects are organized with bazel?

### ISSUE THREAD

**Issue by GinFungYJF** [linuxerwang/gobazel#1]
1. Can you tell any benefits when the projects are organized with bazel?

2. By the way, I think the layout:
```
$TOP
  |- bin/
  |- pkg/
  |- src/
      |- github.com/
      |   |- ...
      |
      |- mycompany.com/
          |- my-prod-1/
          |- my-prod-2/
          |- my-prod-3/
          |- ...

```
should work with both bazel+go_rules and go tools as usual when we add the content of go_prefix to the import paths in the .go files as a prefix.(the go_prefix is part of the directory tree)
For example, A.go in the package my-prod-1:
```
package my-prod-1

import "mycompany.com/my-prod-2"
...
```
Are there anything wrong with it?

**Comment by linuxerwang** [comment]
Sure. This folder layout is useful if your projects involve not only Golang but also Java and other languages. Bazel allows you to put your code (in any language) in any place. For complex projects it's a huge advantage.

So for your 2nd question, it's a standard Golang layout, but the same layout might be awkward for other languages. Bazel provides flexible layouts for all languages. Again, if your projects are not in such complexity, you don't need to use bazel at all.

**Comment by GinFungYJF** [comment]
Got it. Thanks a lot.
