### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by excavador** [linuxerwang/gobazel#4]
Would be great to have tool working under OSX.

**Comment by linuxerwang** [comment]
If I can find a good golang fuse implementation for OSX. I'd suggest OSX users port it since I don't have a OSX device.

**Comment by excavador** [comment]
I made the patch

**Comment by linuxerwang** [comment]
Thank you, excavador.

**Comment by excavador** [comment]
So, should I fix something?...

**Comment by excavador** [comment]
By the way, you can easy check fix.
golang supports cross-compilation

GOOS=darwin go build // extra options

**Comment by linuxerwang** [comment]
Sorry, I forgot to wait for your fix before merge the pull request. Already fixed in the latest commit.

Good point on cross-compilation.

**Comment by excavador** [comment]
No problem!
Did you try cross-compile binary?

**Comment by linuxerwang** [comment]
Just tried. Seems something is wrong:

```bash
$ GOOS=darwin go build -o gobazel-osx github.com/linuxerwang/gobazel
# github.com/rjeczalik/notify
go/src/github.com/rjeczalik/notify/watcher_fsevents.go:49:11: undefined: stream
```

**Comment by excavador** [comment]
```
oleg@macbook-oleg:~/go/src/github.com/linuxerwang/gobazel (git: master) 
➜ GOOS=darwin go build -o gobazel-osx github.com/linuxerwang/gobazel

oleg@macbook-oleg:~/go/src/github.com/linuxerwang/gobazel (git: master) 
➜ go version
go version go1.9 darwin/amd64
oleg@macbook-oleg:~/go/src/github.com/linuxerwang/gobazel (git: master) 

➜ ./gobazel-osx
Error, the command has to be run in a bazel workspace, stat 
/Users/oleg/go/src/github.com/linuxerwang/gobazel/WORKSPACE: no such file or directory

oleg@macbook-oleg:~/go/src/github.com/linuxerwang/gobazel (git: master) 
➜
```

Just checked - it's fine. Interesting, cross-compilation osx => linux works fine, but opposite seems like not.

**Comment by linuxerwang** [comment]
It's weird. But anyway, I'll rely on your judgment for the correctness. ;)

**Comment by excavador** [comment]
Yeah, it works, do not worry.
Thank you for merge.
